### ISSUE TITLE
Remove extra lines for `{% if %}` statement

### ISSUE THREAD

**Issue by HaoboGu** [cargo-generate/cargo-generate#1168]
**Describe the bug**
I'm using `{% if %}` statement for conditional generation. But I found there're lots of empty lines after generation. For example, the following is what's in the template:

```
{% if microcontroller_family == "esp" %}
[target.riscv32imc-esp-espidf]
linker = "ldproxy"
rustflags = [ "--cfg",  "espidf_time64"] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110
{% else %}
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
{% endif %}
{% if microcontroller_family == "rp2040" %}
runner = "probe-rs run --chip rp2040"
rustflags = []
{% elsif microcontroller_family == "esp" %}
runner = "espflash flash --monitor --log-format defmt"
{% else %}
# TODO: use `probe-rs chip list` to get your chip name 
runner = "probe-rs run --chip {{ chip }}"
rustflags = []
{% endif %}
```

If I choose `microcontroller_family = "esp"`, then the generated file is like:

```toml

[target.'cfg(all(target_arch = "arm", target_os = "none"))']


# TODO: use `probe-rs chip list` to get your chip name 
runner = "probe-rs run --chip stm32h7b0vb"
rustflags = []


```

As you can see, several empty lines are generated. I know cargo-generate may just simply replace `"{% if microcontroller_family == "rp2040" %}"` with `""`, but it could be better if cargo-generate detects the whole line, if it matches the template, removes the line.

**make sure you**
- [x] I'm on the latest rust version `rustup update`
- [x] I'm on the latest cargo-generate version `cargo install cargo-generate`
- [x] In case you have an own `.gitconfig`, provide all sections that contains one of: `insteadOf`, `url`

**To Reproduce**
1. see above

**Expected behavior**
The ideal output is like:
```toml
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# TODO: use `probe-rs chip list` to get your chip name 
runner = "probe-rs run --chip stm32h7b0vb"
rustflags = []
```

**Comment by sassman** [comment]
it appears that the [liquid docs offers help](https://shopify.github.io/liquid/basics/whitespace/)

So your code needs this little `-` annotations after `{%` and before `%}` like so:

```
{%- if microcontroller_family == "esp" -%}
[target.riscv32imc-esp-espidf]
linker = "ldproxy"
rustflags = [ "--cfg",  "espidf_time64"] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110
{%- else -%}
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
{% endif %}
{%- if microcontroller_family == "rp2040" -%}
runner = "probe-rs run --chip rp2040"
rustflags = []
{%- elsif microcontroller_family == "esp" -%}
runner = "espflash flash --monitor --log-format defmt"
{%- else -%}
# TODO: use `probe-rs chip list` to get your chip name
runner = "probe-rs run --chip {{ chip }}"
rustflags = []
{%- endif %}
```

**Comment by HaoboGu** [comment]
Ohhhhh yeah, that does the magic. Thanks!
